### ISSUE TITLE
quiet ignore files in eslint

### ISSUE THREAD

**Issue by chilijung** [Canner/eslint-gitstatus#1]
https://github.com/eslint/eslint/issues/5623

**Comment by chilijung** [comment]
https://github.com/Canner/eslint-gitstatus/commit/17604c3d70b1d27059726363134b6d14f7c9f829

**Comment by lukas-gitl** [comment]
So what was done here and how to use it? A description would be very helpful...

**Comment by chilijung** [comment]
@lukas-gitl create a `.eslintignore` file, `eslint-gitstaged` will ignore the files and folders.   https://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories.
